### ISSUE TITLE
Execution error (python ValueError)

### ISSUE THREAD

**Issue by fmalmeida** [cas-bioinf/rboAnalyzer#1]
Executing the conda install command results in nothing, perhaps the the conda channel is not available?

```bash
# The command
conda install -c conda-forge -c bioconda -c schwarz.marek rboanalyzer

# Gives
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - rboanalyzer

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/schwarz.marek/osx-64
  - https://conda.anaconda.org/schwarz.marek/noarch
  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/au-eoed/osx-64
  - https://conda.anaconda.org/au-eoed/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
  - https://conda.anaconda.org/anaconda/osx-64
  - https://conda.anaconda.org/anaconda/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Additionally, is it possible to run the program with more than one query miRNA sequence? Using perhaps, 20 target miRNAs in a multifasta?

**Comment by fmalmeida** [comment]
I figured out that the conda package is only for linux, and that is the problem. However the last question remains.

Is it possible to run the program with more than one query miRNA sequence? Using perhaps, 20 target miRNAs in a multifasta?

Thank you

**Comment by fmalmeida** [comment]
Hi again!

I have actually managed to execute the program, I have seen that it accepts multifasta as query. However, I still get errors. I am trying to run the pipeline using the hairpin miRNA sequences from mirbase against the scaffolds of one genome of interest in which I want to check for the presence of homologs to known miRNAs.

The execution:

```bash
rboAnalyzer -in mirbase_blastn.txt -db BNUT_CHR -q premirna-with-hit.fa -v --skip_missing --html bnut_miRNA.html --csv bnut_miRNA.csv --threads 6 --blast_regexp "Scaffold_\d+"

STATUS: starting rboAnalyzer...
rboAnalyzer - INFO - STATUS: starting rboAnalyzer...
rboAnalyzer - INFO - BLAST file: mirbase_blastn.txt
rboAnalyzer - INFO - Query file: premirna-with-hit.fa
rboAnalyzer - INFO - BLAST db:   BNUT_CHR
rboAnalyzer - INFO - Loading /miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BR_core/config.txt
rboAnalyzer - INFO - Overriding previous configuration.
rboAnalyzer - INFO - blastcmd is installed in required version
rboAnalyzer - INFO - blastcmd is installed in required version
rboAnalyzer - INFO - Locarna is installed in required version
rboAnalyzer - INFO - Locarna is installed in required version
rboAnalyzer - INFO - cmbuild is installed in required version
rboAnalyzer - INFO - cmalign is installed in required version
rboAnalyzer - INFO - RNAfold is installed in required version
rboAnalyzer - INFO - RNAplot is installed in required version
rboAnalyzer - INFO - RNAdistance is installed in required version
rboAnalyzer - INFO - RNAalifold is installed in required version
rboAnalyzer - INFO - refold.pl is instaled in required version
rboAnalyzer - INFO - clustalo is installed in required version
rboAnalyzer - INFO - centroid_homfold is installed in required version
rboAnalyzer - INFO - TruboFold is installed in required version
rboAnalyzer - INFO - hybrid-ss-min could not be located (not in PATH). Please see the manual for installation.
rboAnalyzer - INFO - muslce is installed in required version
rboAnalyzer - INFO - Loading /miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BR_core/config.txt
rboAnalyzer - INFO - Overriding previous configuration.
rboAnalyzer - INFO - Inferred BLAST format: txt.
rboAnalyzer - INFO - blast_parse_txt
STATUS: processing query: ath-MIR156e
rboAnalyzer - INFO - Infer homology - searching RFAM for best matching model.
rboAnalyzer - INFO - Runing cmscan.
Something went wrong.
```

The error:

```python
could not convert string to float: '9   6.3e-'Traceback (most recent call last):
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BA.py", line 460, in main
    _ = lunch_with_args(args)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BA.py", line 559, in lunch_with_args
    _, results = lunch_computation(args)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BR_core/luncher.py", line 96, in lunch_computation
    ih_model, analyzed_hits = find_and_extract_cm_model(args_inner, analyzed_hits)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BR_core/infer_homology.py", line 26, in find_and_extract_cm_model
    cmscan_results = get_cm_model_table(args.blast_query, threads=args.threads)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BR_core/cmalign.py", line 545, in get_cm_model_table
    cmscan_data = parse_cmalign_infernal_table(f)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/rna_blast_analyze/BR_core/cmalign.py", line 516, in parse_cmalign_infernal_table
    pd_out['E-value'] = pd_out['E-value'].astype('float')
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/pandas/core/generic.py", line 5874, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 631, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 673, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/miniconda/envs/rbo/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1097, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: '9   6.3e-'
```

Any thoughts?
